version: '3.8'

services:
  cleanbot:
    build: .
    container_name: cleanbot
    volumes:
      - cleanbot-data:/usr/src/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  cleanbot-data:
